dist: trusty
sudo: false

language: python
python:
  - 3.5

before_install:
  - sh travis/build_weld.sh

install:
  - pip install pipenv
  - sh travis/build_baloo.sh

script:
  - pipenv run pytest tests
  - pipenv run make -C doc doctest
